treely/strapi-slices

- src/components/SliceRenderer/SliceRenderer.tsx
- src/components/portfolio/PortfolioProjectCard/PortfolioProjectCard.test.tsx
- src/components/portfolio/PortfolioProjectCard/PortfolioProjectCard.tsx
- src/components/portfolio/PortfolioProjectCard/index.ts
- src/components/portfolio/PortfolioProjectCard/messages.de.ts
- src/components/portfolio/PortfolioProjectCard/messages.en.ts
- src/models/PortfolioProject.ts
- src/models/strapi/StrapiProject.ts
- src/models/strapi/StrapiProjectCard.ts
- src/rootMessages.de.ts
- src/rootMessages.en.ts
- src/slices/ProjectsGrid/ProjectsGrid.stories.tsx
- src/slices/ProjectsGrid/ProjectsGrid.test.tsx
- src/slices/ProjectsGrid/ProjectsGrid.tsx
- src/slices/TextWithCard/TextWithCard.stories.tsx
- src/slices/TextWithCard/TextWithCard.test.tsx
- src/slices/TextWithCard/TextWithCard.tsx
- src/test/integrationMocks/portfolioProjectMock.ts
- src/test/strapiMocks/strapiProject.ts
- src/test/strapiMocks/strapiProjectCard.ts
BREAKING CHANGE: This requires that the area and location are set in the FPM. Futhermore, a thumbnail image and a certification state need to be set in Strapi.
> breaking(ProjectCard): Use area and location from FPM

- README.md
- src/utils/mergeGlobalAndStrapiBlogPostData.test.ts
- src/utils/mergeGlobalAndStrapiBlogPostData.ts
- src/utils/mergeGlobalAndStrapiCustomerStoryData.test.ts
- src/utils/mergeGlobalAndStrapiCustomerStoryData.ts
- src/utils/mergeGlobalAndStrapiPageData.test.ts
- src/utils/mergeGlobalAndStrapiPageData.ts
- src/utils/mergeGlobalAndStrapiProjectData.test.ts
- src/utils/mergeGlobalAndStrapiProjectData.ts
> feat: Only return needed data in merge functions

- src/components/SliceRenderer/SliceRenderer.tsx
- src/rootMessages.de.ts
- src/rootMessages.en.ts
- src/slices/Timeline/Timeline.stories.tsx
- src/slices/Timeline/Timeline.test.tsx
- src/slices/Timeline/Timeline.tsx
- src/slices/Timeline/index.ts
- src/slices/Timeline/messages.de.ts
- src/slices/Timeline/messages.en.ts
Preview: https://storybook-qxyg5vcl0-treely.vercel.app/?path=/story/slices-timeline--minimal
> Add Timeline component

- src/slices/TextWithCard/TextWithCard.stories.tsx
> fix: Set projects prop in TextWithCard section in storybook

- src/slices/Timeline/Timeline.tsx
Preview: https://storybook-n8x84mpjd-treely.vercel.app/?path=/story/slices-comparison--white
> fix: Fix the width of the component

- src/slices/Cta/Cta.tsx
Issue: https://github.com/treely/app/issues/962
> Add margin right in text in Cta

- src/slices/QuoteCards/QuoteCards.tsx
Fixes https://github.com/treely/app/issues/978
> fix(QuoteCards): Fix Button in Header

- src/components/LogoCard/LogoCard.test.tsx
- src/components/LogoCard/LogoCard.tsx
- src/components/LogoCard/index.ts
- src/models/strapi/StrapiCustomerStory.ts
- src/slices/CustomerStories/CustomerStories.stories.tsx
- src/slices/CustomerStories/CustomerStories.tsx
- src/test/strapiMocks/strapiCustomerStory.ts
Preview: https://storybook-qwqkcn7t2-treely.vercel.app/?path=/story/slices-customerstories--with-logo-card
Story: https://trello.com/c/Zl38LJKR/405-customer-logo-card-3-8
> feat(LogoCard): Create LogoCard component

- package-lock.json
- package.json
- src/slices/TextCarousel/TextCarousel.tsx
- src/slices/TextCarousel/styles.ts
Impediment: https://trello.com/c/JG2Xg71C/465-textcarousel-updates
Preview:  https://storybook-k9o4ap7ai-treely.vercel.app/?path=/story/slices-textcarousel--minimal
> fix(TextCarousel): Fix the component

- src/slices/IconGrid/IconGrid.tsx
Preview: https://storybook-p9nhl7cmi-treely.vercel.app/?path=/story/slices-icongrid--minimal
> fix(IconGrid):  Update the breakpoints of the grid

- src/slices/TextCarousel/TextCarousel.tsx
- src/slices/TextCarousel/styles.ts
https://storybook-o3n9l683q-treely.vercel.app/?path=/story/slices-textcarousel--minimal
> fix(TextCarousel): Fix three elements width

- src/slices/FullWidthImageSlider/FullWidthImageSlider.tsx
- src/slices/FullWidthImageSlider/styles.ts
https://github.com/treely/strapi-slices/issues/75
https://storybook-2j0b2c2wv-treely.vercel.app/?path=/story/slices-fullwidthimageslider--default
> fix(FullWidthImageSlider): Fix scrolling in FullWidthImageSlider

- src/components/portfolio/SmallCheckout/SmallCheckout.tsx
Impediment: https://trello.com/c/pgRLRSRB/494-0-always-stays-in-checkout-form-if-not-marking-the-full-text
> fix(SmallCheckout): Fix 0 in contribution value input

- src/components/portfolio/SmallCheckout/SmallCheckout.tsx
- src/models/forms/SmallCheckoutForm.ts
Issue: https://github.com/treely/strapi-slices/issues/89
> fix(SmallCheckout): Fix the error of value NaN in SmallCheckout test

- src/components/portfolio/SmallCheckout/SmallCheckout.test.tsx
- src/components/portfolio/SmallCheckout/SmallCheckout.tsx
- src/components/portfolio/SmallCheckout/messages.de.ts
- src/components/portfolio/SmallCheckout/messages.en.ts
- src/slices/ProjectFacts/ProjectFacts.stories.tsx
- src/slices/ProjectFacts/ProjectFacts.tsx
Story: https://trello.com/c/hekPRzbh/473-include-vat-in-shop-checkouts-on-website-3-8
> feat(ProjectFacts): Add taxInPercent prop

- package-lock.json
- src/slices/ShopCheckout/ShopCheckout.stories.tsx
- src/slices/ShopCheckout/ShopCheckout.test.tsx
- src/slices/ShopCheckout/ShopCheckout.tsx
- src/slices/ShopCheckout/messages.de.ts
- src/slices/ShopCheckout/messages.en.ts
Story: https://trello.com/c/hekPRzbh/473-include-vat-in-shop-checkouts-on-website-3-8
> feat(ShopCheckout): Add taxInPercent prop

- src/slices/TextCardGrid/TextCardGrid.tsx
https://trello.com/c/XrVhlIVo/536-increase-max-number-of-cards-in-textcardgrid-to-100
> feat(textcardgrid): allow infinite number of cards

- src/components/portfolio/ProjectInfo/ProjectInfo.test.tsx
- src/components/portfolio/ProjectInfo/ProjectInfo.tsx
- src/components/portfolio/ProjectInfo/messages.de.ts
- src/components/portfolio/ProjectInfo/messages.en.ts
Issue: https://trello.com/c/LkiMD7uw/542-tooltip-portfolio-page-projectfacts-slice
> feat: add tooltip to portfolio page

- src/slices/TextCarousel/TextCarousel.stories.tsx
- src/slices/TextCarousel/TextCarousel.tsx
- src/utils/shuffleElements.test.ts
- src/utils/shuffleElements.ts
Impediment: https://trello.com/c/XFwVo7CR/602-textcarousel-update-for-mobile-desktop
TODO: Update strapi repo
> feat: enable shuffle cards feature

- .storybook/preview.tsx
- __mocks__/swr/index.ts
- __mocks__/swr/infinite.ts
- package-lock.json
- package.json
- src/components/ContextProvider/ContextProvider.tsx
- src/components/EventCard/EventCard.test.tsx
- src/components/EventCard/EventCard.tsx
- src/components/EventCard/index.ts
- src/components/EventCard/messages.de.ts
- src/components/EventCard/messages.en.ts
- src/components/SliceRenderer/SliceRenderer.tsx
- src/components/StrapiLinkButton/StrapiLinkButton.tsx
- src/index.tsx
- src/models/SWRData.ts
- src/models/hooks/UseInfiniteDataHookProps.tsx
- src/models/hooks/useEvents.ts
- src/models/strapi/StrapiEvent.ts
- src/rootMessages.de.ts
- src/rootMessages.en.ts
- src/slices/Events/Events.stories.tsx
- src/slices/Events/Events.test.tsx
- src/slices/Events/Events.tsx
- src/slices/Events/index.ts
- src/slices/Events/messages.de.ts
- src/slices/Events/messages.en.ts
- src/test/strapiMocks/strapiEventMock.ts
- src/utils/getCountryFlag.test.ts
- src/utils/getCountryFlag.ts
- src/utils/strapiMediaUrl.ts
Story: https://trello.com/c/SSlIWhrM/590-new-event-cards-page-8-21
Design: https://www.figma.com/design/UMVmWAOhEEhM1ohmFO4dVU/Event-Cards?node-id=519-1455&m=dev
Filter search will be implemented in another PR
> feat: implement event-cards

- src/components/EventCard/EventCard.test.tsx
- src/components/EventCard/EventCard.tsx
- src/models/strapi/StrapiEvent.ts
- src/slices/Events/Events.test.tsx
- src/slices/Events/Events.tsx
Preview: https://storybook-lzlg4ng90-treely.vercel.app/?path=/story/slices-events--with-filter-search
> feat: update filter, make speakers and button optional

- src/slices/Events/Events.stories.tsx
- src/slices/Events/Events.tsx
impediment: https://trello.com/c/FDHWyJip/691-eventcards-spacing
Preview: https://storybook-o1hlm0y7l-treely.vercel.app/?path=/story/slices-events--minimal
> fix: fix event-card length and events title length

- src/slices/Events/Events.tsx
Impediment: https://trello.com/c/HkhlPWcu/703-only-two-events-are-shown-in-events-page
Preview: https://storybook-6iwibly2y-treely.vercel.app/?path=/story/slices-events--with-filter-search
> fix: fix pagination

- .gitignore
- package-lock.json
- package.json
- src/components/SEOTags/SEOTags.tsx
Impediment: https://trello.com/c/xtZNaP9U/127-add-schema-markups-to-our-website
> feat: option to pass schema markups to seotags

- src/components/SEOTags/SEOTags.tsx
As this library is used among other projects, I think there should be no default/fallback schema markup.
> feat: remove default schema markup
